### ISSUE TITLE
Try TMBad framework

### ISSUE THREAD

**Issue by seananderson** [carrieholt/KF-funcs#3]
Exciting to see the Kalman filter TMB work! @catarinawor, you might want to try the new TMBad autodiff framework. It's tended to be ~3 times faster in models I've tried.

You can probably just add `framework = 'TMBad'` in the `compile()` function calls here: https://github.com/carrieholt/KF-funcs/blob/cea1ec92f847f30e6db431a950b3d8b968c02a0e/src/Makefile.win#L7

(Or set `options(tmb.ad.framework = 'TMBad')`)

The other option is in a Makevars file like this https://github.com/pbs-assess/sdmTMB/blob/main/src/Makevars but I'm not sure if that will affect your compilation.

**Comment by catarinawor** [comment]
Awesome! Thanks for the Tip, Sean!
